twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'recaptcha.html.twig'
